<a href="https://colab.research.google.com/github/25007500-ai/data-science-tutorial/blob/main/Tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tidy Data, Data Characteristics

1. Find some real dataset. Load it on Colab, Kaggle etc. Try to visualize some of it

2. Evaluate if the data is good or not. Does it have enough samples?

3. How many features does it have? Is it enough?

4. How many samples/observation does it have? Is it enough?

5. What are the datatypes does the dataset consist of?

6. How many columns have null values? If yes, which column, which rows

7. Which column is the feature, which is the target output?

8. Does it have missing values? If yes, which column, which row.

9. What kind of question can be asked, should we ask. Does the dataset suits the question we are asking?

In [56]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [57]:
import pandas as pd
import numpy as np

In [58]:
df=pd.read_excel("/content/drive/MyDrive/data science/record.xlsx")
df

    Name Grade Obedient  ResearchScore  ProjectScore Recommend
0   Ryan     A        Y             90            85       Yes
1   John     C        Y             85            51       Yes
2  Kevin   NaN      NaN             10            17        No
3    Tom     B        Y             75            71        No
4  Freya     E      NaN             20            30        No
5  Simon     A        Y             92            79       Yes
6   Ezra   NaN        Y             60            59        No
7   Alex     C      NaN             75            33        No

based on the data
which has only 8 rows and 5 colums,this is not enough or suitable for future prediction or to build an accurate machine learning model

In [59]:
df.head(5)

    Name Grade Obedient  ResearchScore  ProjectScore Recommend
0   Ryan     A        Y             90            85       Yes
1   John     C        Y             85            51       Yes
2  Kevin   NaN      NaN             10            17        No
3    Tom     B        Y             75            71        No
4  Freya     E      NaN             20            30        No

In [60]:
df.tail(2)

   Name Grade Obedient  ResearchScore  ProjectScore Recommend
6  Ezra   NaN        Y             60            59        No
7  Alex     C      NaN             75            33        No

In [61]:
df.shape

(8, 6)

In [62]:
df.describe()

       ResearchScore  ProjectScore
count       8.000000      8.000000
mean       63.375000     53.125000
std        31.640559     24.752705
min        10.000000     17.000000
25%        50.000000     32.250000
50%        75.000000     55.000000
75%        86.250000     73.000000
max        92.000000     85.000000

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           8 non-null      object
 1   Grade          6 non-null      object
 2   Obedient       5 non-null      object
 3   ResearchScore  8 non-null      int64
 4   ProjectScore   8 non-null      int64
 5   Recommend      8 non-null      object
dtypes: int64(2), object(4)
memory usage: 516.0+ bytes

In [64]:
df.isnull().sum()

Name             0
Grade            2
Obedient         3
ResearchScore    0
ProjectScore     0
Recommend        0
dtype: int64

In [65]:
df.isnull()

    Name  Grade  Obedient  ResearchScore  ProjectScore  Recommend
0  False  False     False          False         False      False
1  False  False     False          False         False      False
2  False   True      True          False         False      False
3  False  False     False          False         False      False
4  False  False      True          False         False      False
5  False  False     False          False         False      False
6  False   True     False          False         False      False
7  False  False      True          False         False      False